---
title: "Create Test Data"
output: html_document
---

```{r library}
library(fluvgeo)
library(usethis)
library(arcgisbinding)
arc.check_product()
```

# Study Area
Data for tests was taken from the Sinsinawa Creek, IL study area. 

# ESRI File Geodatabase
Test data in ESRI ArcGIS file geodatabase format is stored in 
`fluvgeo/inst/extdata/testing_data.gdb`
`fluvgeo/inst/extdata/testing_raster.gdb`

Convert a file geodatabase feature class to an sp object
```{r import}
# Path to data
data_path <- "D:/Workspace/EMRRP_Sediment/Methods/fluvgeo/inst/extdata/testing_data.gdb/"

# Import geospatial datasets
sin_flowline_sp                 <- fluvgeo::arc2sp(paste0(data_path, "flowline"))
sin_flowline_points_sp          <- fluvgeo::arc2sp(paste0(data_path, "flowline_points"))
sin_banklines_sp                <- fluvgeo::arc2sp(paste0(data_path, "banklines"))
sin_bankline_points_sp          <- fluvgeo::arc2sp(paste0(data_path, "bankline_points"))
sin_features_sp                 <- fluvgeo::arc2sp(paste0(data_path, "features"))
sin_loop_points_sp              <- fluvgeo::arc2sp(paste0(data_path, "loop_points"))
sin_riffle_channel_sp           <- fluvgeo::arc2sp(paste0(data_path, "riffle_channel"))
sin_riffle_channel_points_sp    <- fluvgeo::arc2sp(paste0(data_path, "riffle_channel_points"))
sin_riffle_floodplain_sp        <- fluvgeo::arc2sp(paste0(data_path, "riffle_floodplain"))
sin_riffle_floodplain_points_sp <- fluvgeo::arc2sp(paste0(data_path, "riffle_floodplain_points"))
sin_riffle_floodplain_dims_L1_sp <- fluvgeo::arc2sp(paste0(data_path, "riffle_floodplain_dims_L1"))
sin_riffle_floodplain_dims_L2_sp <- fluvgeo::arc2sp(paste0(data_path, "riffle_floodplain_dims_L2"))
sin_riffle_floodplain_dims_L3_sp <- fluvgeo::arc2sp(paste0(data_path, "riffle_floodplain_dims_L3"))
sin_valleyline_sp               <- fluvgeo::arc2sp(paste0(data_path, "valleyline"))
sin_valleyline_points_sp        <- fluvgeo::arc2sp(paste0(data_path, "valleyline_points"))
sin_gradient_sp                 <- fluvgeo::arc2sp(paste0(data_path, "gradient_1"))
```

```{r}
# convert to .rda files
usethis::use_data(sin_flowline_sp, overwrite = TRUE)
usethis::use_data(sin_flowline_points_sp, overwrite = TRUE)
usethis::use_data(sin_banklines_sp, overwrite = TRUE)
usethis::use_data(sin_bankline_points_sp, overwrite = TRUE)
usethis::use_data(sin_features_sp, overwrite = TRUE)
usethis::use_data(sin_loop_points_sp, overwrite = TRUE)
usethis::use_data(sin_riffle_channel_sp, overwrite = TRUE)
usethis::use_data(sin_riffle_channel_points_sp, overwrite = TRUE)
usethis::use_data(sin_riffle_floodplain_sp, overwrite = TRUE)
usethis::use_data(sin_riffle_floodplain_points_sp, overwrite = TRUE)
usethis::use_data(sin_riffle_floodplain_dims_L1_sp, overwrite = TRUE)
usethis::use_data(sin_riffle_floodplain_dims_L2_sp, overwrite = TRUE)
usethis::use_data(sin_riffle_floodplain_dims_L3_sp, overwrite = TRUE)
usethis::use_data(sin_valleyline_sp, overwrite = TRUE)
usethis::use_data(sin_valleyline_points_sp, overwrite = TRUE)
usethis::use_data(sin_gradient_sp, overwrite = TRUE)
```


