---
title: "Create Test Data"
output: html_document
---

```{r library}
library(fluvgeo)
library(usethis)
library(arcgisbinding)
arc.check_product()
```

# Study Area
Data for tests was taken from the Sinsinawa Creek, IL study area. 

# ESRI File Geodatabase
Test data in ESRI ArcGIS file geodatabase format is stored in 
`fluvgeo/inst/extdata/testing_data.gdb`
`fluvgeo/inst/extdata/testing_raster.gdb`

Convert a file geodatabase feature class to an sf object
```{r import}
# Path to data
data_path <- "C:/workspace/fluvgeo/inst/extdata/testing_data.gdb/feature_dataset/"

# Import geospatial datasets
sin_flowline_sf                 <- fluvgeo::arc2sf(paste0(data_path, 
                                                "flowline"))
sin_flowline_points_sf          <- fluvgeo::arc2sf(paste0(data_path, 
                                                "flowline_points"))
sin_banklines_sf                <- fluvgeo::arc2sf(paste0(data_path, 
                                                "banklines"))
sin_bankline_points_sf          <- fluvgeo::arc2sf(paste0(data_path, 
                                                "bankline_points"))
sin_features_sf                 <- fluvgeo::arc2sf(paste0(data_path, 
                                                "features"))
sin_loop_points_sf              <- fluvgeo::arc2sf(paste0(data_path, 
                                                "loop_points"))
sin_riffle_channel_sf           <- fluvgeo::arc2sf(paste0(data_path, 
                                                "riffle_channel"))
sin_riffle_channel_points_sf    <- fluvgeo::arc2sf(paste0(data_path, 
                                                "riffle_channel_points"))
sin_riffle_floodplain_sf        <- fluvgeo::arc2sf(paste0(data_path, 
                                                "riffle_floodplain"))
sin_riffle_floodplain_points_sf <- fluvgeo::arc2sf(paste0(data_path, 
                                                "riffle_floodplain_points"))
sin_riffle_floodplain_dims_L1_sf <- fluvgeo::arc2sf(paste0(data_path, 
                                                "riffle_floodplain_dims_L1"))
sin_riffle_floodplain_dims_L2_sf <- fluvgeo::arc2sf(paste0(data_path, 
                                                "riffle_floodplain_dims_L2"))
sin_riffle_floodplain_dims_L3_sf <- fluvgeo::arc2sf(paste0(data_path, 
                                                 "riffle_floodplain_dims_L3"))
sin_valleyline_sf               <- fluvgeo::arc2sf(paste0(data_path, 
                                                 "valleyline"))
sin_valleyline_points_sf        <- fluvgeo::arc2sf(paste0(data_path, 
                                                 "valleyline_points"))
sin_gradient_sf                 <- fluvgeo::arc2sf(paste0(data_path, 
                                                 "gradient_1"))
```

```{r}
# convert to .rda files
usethis::use_data(sin_flowline_sf, overwrite = TRUE)
usethis::use_data(sin_flowline_points_sf, overwrite = TRUE)
usethis::use_data(sin_banklines_sf, overwrite = TRUE)
usethis::use_data(sin_bankline_points_sf, overwrite = TRUE)
usethis::use_data(sin_features_sf, overwrite = TRUE)
usethis::use_data(sin_loop_points_sf, overwrite = TRUE)
usethis::use_data(sin_riffle_channel_sf, overwrite = TRUE)
usethis::use_data(sin_riffle_channel_points_sf, overwrite = TRUE)
usethis::use_data(sin_riffle_floodplain_sf, overwrite = TRUE)
usethis::use_data(sin_riffle_floodplain_points_sf, overwrite = TRUE)
usethis::use_data(sin_riffle_floodplain_dims_L1_sf, overwrite = TRUE)
usethis::use_data(sin_riffle_floodplain_dims_L2_sf, overwrite = TRUE)
usethis::use_data(sin_riffle_floodplain_dims_L3_sf, overwrite = TRUE)
usethis::use_data(sin_valleyline_sf, overwrite = TRUE)
usethis::use_data(sin_valleyline_points_sf, overwrite = TRUE)
usethis::use_data(sin_gradient_sf, overwrite = TRUE)
```


