---
title: "Plot Tests"
output: html_document
---

```{r}
library(arcgisbinding)
library(ggplot2)
library(tidyr)
library(ggrepel)
library(conicfit)
library(resri)
library(sp)
library(raster)
library(tmap)
library(tmaptools)
library(OpenStreetMap)
library(scales)
library(grDevices)
library(colorspace)

# Checkout an ArcGIS license
arc.check_product()
```

# XS Profile Plot
```{r}
# Import xs dimensions feature class
sen_xs_dimensions <- fluvgeo::arc2sp("Z:/Work/Office/Regional/ERDC/EMRRP_Sediment/Senachwine/Data/Watershed/03_SenachwineCreekMainstem/SenachwineCreekMainstem.gdb/riffle_dims_104")

# Import infrastructure feature class
sen_infrastructure <- fluvgeo::arc2sp("Z:/Work/Office/Regional/ERDC/EMRRP_Sediment/Senachwine/Data/Watershed/03_SenachwineCreekMainstem/SenachwineCreekMainstem.gdb/infrastructure")

# Convert to a dataframe
sen_xs_dims <- sen_xs_dimensions@data
sen_infra <- sen_infrastructure@data
```


```{r}
xs_profile_plot(sen_xs_dims, sen_infra, label_xs = TRUE)
```

```{r}
# Import xs dimensions feature class
sen01_xs_dimensions <- fluvgeo::arc2sp("Z:/Work/Office/Regional/ERDC/EMRRP_Sediment/Senachwine/Data/Watershed/01_LowerSenachwineCreek/LowerSenachwineCreek.gdb/riffle_channel_dims_planform")

# Convert to a dataframe
sen01_xs_dims <- sen01_xs_dimensions@data
```

```{r}
# Import xs features feature class
sen01_features <- fluvgeo::arc2sp("Z:/Work/Office/Regional/ERDC/EMRRP_Sediment/Senachwine/Data/Watershed/01_LowerSenachwineCreek/LowerSenachwineCreek.gdb/features")

# Convert to a dataframe
sen01_feat <- sen01_features@data
```


```{r}
# Profile plot
xs_profile_plot(sen01_xs_dims, sen01_feat, label_xs = TRUE)
```


# XS Metrics Plot
```{r fig.width=7, fig.height=9, warning=FALSE}
xs_metrics_plot(sen01_xs_dims, label_xs = TRUE)
```


# Planform 
```{r}
# Import bankline points feature class
bankline_points_fc <- fluvgeo::arc2sp("Z:/Work/Office/Regional/ERDC/EMRRP_Sediment/Senachwine/Data/Watershed/01_LowerSenachwineCreek/LowerSenachwineCreek.gdb/bankline_points")

# Convert to a dataframe
bankline_pts <- bankline_points_fc@data
```

## Bend Radius
```{r eval=FALSE}
bend_raduis_plot(bankline_pts, loop =19, bend = 1, "UTM 16N")
```

```{r}
bends <- bend_radius(bankline_pts)
```

## Loop length
```{r}
loop_length <- meander_length(bankline_pts)
```

## Loop Width
```{r}
loop_width <- meander_width(bankline_pts)
```

```{r}
bends_planform <- planform(bankline_pts)
```


# Reach Metrics Report
## Lower Senachwine Creek
```{r}
# Import xs dimensions feature class
sen01_xs_points <- fluvgeo::arc2sp("Z:/Work/Office/Regional/ERDC/EMRRP_Sediment/Senachwine/Data/Watershed/01_LowerSenachwineCreek/LowerSenachwineCreek.gdb/riffle_channel_points")

# Convert to a dataframe
sen01_xs_pts <- sen01_xs_points@data

# Import xs dimensions feature class
sen01_xs_dimensions <- fluvgeo::arc2sp("Z:/Work/Office/Regional/ERDC/EMRRP_Sediment/Senachwine/Data/Watershed/01_LowerSenachwineCreek/LowerSenachwineCreek.gdb/riffle_channel_dims_planform")

# Import bankline points feature class
banklines <- fluvgeo::arc2sp("Z:/Work/Office/Regional/ERDC/EMRRP_Sediment/Senachwine/Data/Watershed/01_LowerSenachwineCreek/LowerSenachwineCreek.gdb/banklines")

dem_path <- "Z:/Work/Office/Regional/ERDC/EMRRP_Sediment/Senachwine/Data/Watershed/01_LowerSenachwineCreek/LowerSenachwineCreek.gdb/dem"

# Import xs features feature class
sen01_features <- fluvgeo::arc2sp("Z:/Work/Office/Regional/ERDC/EMRRP_Sediment/Senachwine/Data/Watershed/01_LowerSenachwineCreek/LowerSenachwineCreek.gdb/features")

# Convert to a dataframe
sen01_feat <- sen01_features@data
```


```{r}
xs_metrics_report(xs_points = sen01_xs_pts[sen01_xs_pts$Seq > 0, ],
                  xs_dims_planform = sen01_xs_dimensions,
                  dem = dem_path,
                  banklines = banklines,
                  extent_factor = 3,
                  streams = c("Lower Senachwine Creek"), 
                  regions = c("Illinois River", "IL River Panther Creek"), 
                  features = sen01_feat,
                  label_xs = TRUE,
                  output_dir = "Z:/Work/Office/Regional/ERDC/EMRRP_Sediment/Senachwine/Data/Watershed/01_LowerSenachwineCreek",
                  output_format = "word_document")
```

## Campbell Creek
```{r}
# Import xs dimensions feature class
cam_xs_points <- fluvgeo::arc2sp("Z:/Work/Office/Regional/ERDC/EMRRP_Sediment/CampbellsCreek/CampbellCreek.gdb/riffle_points")

# Convert to a dataframe
cam_xs_pts <- cam_xs_points@data

# Import xs dimensions feature class
cam_xs_dimensions <- fluvgeo::arc2sp("Z:/Work/Office/Regional/ERDC/EMRRP_Sediment/CampbellsCreek/CampbellCreek.gdb/riffle_dims_planform")

# convert tot data frame
cam_xs_dimensions_df <- cam_xs_dimensions@data

# Import bankline points feature class
cam_banklines <- fluvgeo::arc2sp("Z:/Work/Office/Regional/ERDC/EMRRP_Sediment/CampbellsCreek/CampbellCreek.gdb/banklines")

cam_dem_path <- "Z:/Work/Office/Regional/ERDC/EMRRP_Sediment/CampbellsCreek/CampbellCreek.gdb/dem_hydro"

# Import xs features feature class
cam_features <- fluvgeo::arc2sp("Z:/Work/Office/Regional/ERDC/EMRRP_Sediment/CampbellsCreek/CampbellCreek.gdb/features")

# Convert to a dataframe
cam_feat <- cam_features@data
```

```{r}
# Profile plot
xs_profile_plot(cam_xs_dimensions_df)
```


# XS Metrics Plot
```{r fig.width=7, fig.height=9, warning=FALSE}
xs_metrics_plot(cam_xs_dimensions_df)
```


```{r}
xs_metrics_report(xs_points = cam_xs_pts,
                  xs_dims_planform = cam_xs_dimensions,
                  dem = cam_dem_path,
                  banklines = cam_banklines,
                  extent_factor = 3,
                  streams = c("Campbel Creek"), 
                  regions = c("Eastern United States"), 
                  features = cam_feat,
                  label_xs = TRUE,
                  output_dir = "Z:/Work/Office/Regional/ERDC/EMRRP_Sediment/CampbellsCreek/Analysis",
                  output_format = "word_document")
```



# Estimate Bankfull
```{r}
estimate_bankfull(xs_points = sen01_xs_pts, 
                  streams = c("Lower Senachwine Creek"), 
                  regions = c("Illinois River", "IL River Panther Creek"), 
                  bankfull_elevations = seq(101, 108, 0.2),
                  bf_estimate = 105, 
                  stat = "MAE",
                  output_dir = "Z:/Work/Office/Regional/ERDC/EMRRP_Sediment/Senachwine/Data/Watershed/01_LowerSenachwineCreek", 
                  output_format = "word_document")
```



# Site Map

```{r}
# Import bankline points feature class
banklines <- fluvgeo::arc2sp("Z:/Work/Office/Regional/ERDC/EMRRP_Sediment/Senachwine/Data/Watershed/01_LowerSenachwineCreek/LowerSenachwineCreek.gdb/banklines")

# Import xs dimensions feature class
sen01_xs_dimensions <- fluvgeo::arc2sp("Z:/Work/Office/Regional/ERDC/EMRRP_Sediment/Senachwine/Data/Watershed/01_LowerSenachwineCreek/LowerSenachwineCreek.gdb/riffle_channel_dims_planform")
```

```{r}
dem_arc <- arc.open("Z:/Work/Office/Regional/ERDC/EMRRP_Sediment/Senachwine/Data/Watershed/01_LowerSenachwineCreek/LowerSenachwineCreek.gdb/dem")
#dem <- arc.raster(dem_arc)
```

```{r}
#' @title Calculate XS Map extent
xs_extent <- function(orig_xs_extent, multiplier) {
  # Calculate centroid of extent
  x_center <- ((orig_xs_extent@xmax - orig_xs_extent@xmin) / 2) + orig_xs_extent@xmin
  y_center <- ((orig_xs_extent@ymax - orig_xs_extent@ymin) / 2) + orig_xs_extent@ymin
  
  # Determine the extent furthest from the centroid
  x_center_dist <- orig_xs_extent@xmax - x_center
  y_center_dist <- orig_xs_extent@ymax - y_center
  max_dim <- max(c(x_center_dist, y_center_dist))
  
  # Create the new extent
  xmin <- x_center - (max_dim * multiplier)
  xmax <- x_center + (max_dim * multiplier)
  ymin <- y_center - (max_dim * multiplier)
  ymax <- y_center + (max_dim * multiplier)
  extent <- c(xmin, xmax, ymin, ymax)
  
  # Create a list of parameters for testing
  params <- list(x_center = x_center, 
              y_center = y_center, 
              x_center_dist = x_center_dist, 
              y_center_dist = y_center_dist, 
              max_dim = max_dim,
              extent = extent)
  
  # Calculate new xs map extent
  xs_map_extent <- raster::extent(extent)
  return(xs_map_extent)
}  
```


```{r}
rm(dem_i)
gc()

i = 3
xs_i <- sen01_xs_dimensions[sen01_xs_dimensions$Seq == i, ]
ext_xs_i <- raster::extent(xs_i)
ext_map_xs_i <- xs_extent(ext_xs_i, 7)
dem_i <- raster::crop(as.raster(arc.raster(dem_arc)), ext_map_xs_i)
```

```{r}
slp <- raster::terrain(dem_i, opt = "slope", unit = "radians")
asp <- raster::terrain(dem_i, opt = "aspect", unit = "radians")
hill <- raster::hillShade(slope = slp, aspect = asp)
```


```{r}
# Create topo color ramp
esri_topo <- colorRampPalette(colors = c("cadetblue2", "khaki1", "chartreuse4", 
                                         "goldenrod1", "orangered4", "saddlebrown", 
                                         "gray70", "white"),
                              bias = 1,
                              space = "Lab",
                              interpolate = "linear")
```


```{r}
tm_shape(hill) + 
  tm_raster(style = "cont",
            palette = grey(0:100/100),
            legend.show = FALSE) + 
tm_shape(dem_i,
         unit = "ft",
         is.master = TRUE) +
  tm_raster(col = "Band_1",
            style = "cont",
            palette = esri_topo(1000),
            alpha = 0.8,
            title = "Elevation (NAVD88, ft)",
            legend.show = TRUE) +
tm_shape(xs_i) + 
  tm_lines(col = "black", lwd = 5) +
tm_shape(sen01_xs_dimensions) + 
  tm_lines(col = "black", lwd = 1) + 
  tm_text(text = "Seq", 
          auto.placement = FALSE,
          xmod = 0.7, ymod = 0.7) +
tm_shape(banklines) + 
  tm_lines(col = "blue", lwd = 1) +
tm_compass(type = "arrow", 
           position = c("right", "bottom")) + 
tm_scale_bar(width = 0.25, 
             position = c("left", "bottom")) + 
tm_layout(main.title = paste("Cross Section", i),
          legend.outside = TRUE,
          legend.outside.position = "right",
          frame.lwd = 3)
```


```{r}
dem_path <- "Z:/Work/Office/Regional/ERDC/EMRRP_Sediment/Senachwine/Data/Watershed/01_LowerSenachwineCreek/LowerSenachwineCreek.gdb/dem"
banklines <- fluvgeo::arc2sp("Z:/Work/Office/Regional/ERDC/EMRRP_Sediment/Senachwine/Data/Watershed/01_LowerSenachwineCreek/LowerSenachwineCreek.gdb/banklines")
sen01_xs_dimensions <- fluvgeo::arc2sp("Z:/Work/Office/Regional/ERDC/EMRRP_Sediment/Senachwine/Data/Watershed/01_LowerSenachwineCreek/LowerSenachwineCreek.gdb/riffle_channel_dims_planform")
sen01_xs_dimensions_df <- sen01_xs_dimensions@data
sen01_flowline <- fluvgeo::arc2sp("Z:/Work/Office/Regional/ERDC/EMRRP_Sediment/Senachwine/Data/Watershed/01_LowerSenachwineCreek/LowerSenachwineCreek.gdb/flowline")
```

```{r results}
xs_number <- 16
xs_map(xs_fc = sen01_xs_dimensions, 
       xs_number = xs_number,
       dem = dem_path,
       banklines = banklines,
       extent_factor = 2)
```

```{r}
# Define metric objects
wdr3 <- new(Class = "FluvialGeomorphicMetric",
            metric = "Width Depth Ratio",
            definition = "bankfull width / bankfull depth",
            variable = "xs_width_depth_ratio",
            threshold_breaks = c(0, 10, 20, Inf),
            threshold_labels = c("Incised",
                                 "Stable",
                                 "Overwidened"),
            source = "Dunn & Leopold, 1978")

rc_bfw <- new(Class = "FluvialGeomorphicMetric",
              metric = "Radius of Curvature to Bankfull Width Ratio",
              definition = "radius of curvature / bankfull width",
              variable = "rc_bfw_ratio",
              threshold_breaks = c(0, 1.6, 2.0, Inf),
              threshold_labels = c("Unstable",
                                   "Relatively Stable",
                                   "Stable"),
              source = "Haring, personal communication")

wdr4 <- new(Class = "FluvialGeomorphicMetric",
            metric = "Width Depth Ratio",
            definition = "bankfull width / bankfull depth",
            variable = "xs_width_depth_ratio",
            threshold_breaks = c(0, 5, 10, 20, Inf),
            threshold_labels = c("Incised",
                                 "Sorta Stable",
                                 "Stable",
                                 "Overwidened"),
            source = "Dunn & Leopold, 1978")
```

```{r}
flowline      <- sen01_flowline
xs_dimensions <- sen01_xs_dimensions
```

```{r reach_overview_map, fig.width=6}
reach_overview_map(flowline, xs_dimensions)
```


```{r reach_metric_map, fig.width=6}
reach_metric_map(wdr4, flowline, xs_dimensions)
```

```{r xs_metric_plot, fig.width=6}
xs_metric_plot(wdr4, sen01_xs_dimensions_df)
```


