---
output: word_document
---

```{r, library, include=FALSE}
library(fluvgeo)
library(assertthat)
library(dplyr)
library(knitr)
library(rmarkdown)
library(Metrics)
library(ggplot2)
library(ggrepel)
library(reshape2)
library(kableExtra)
library(arcgisbinding)
library(tmap)
arc.check_product()
```

# Sinsinawa
```{r}
xs_points_sp <- arc2sp("Z:/Work/Office/Regional/ERDC/EMRRP_Sediment/Methods/fluvgeo/inst/extdata/testing_data.gdb/riffle_floodplain_points")
xs_points_df <- xs_points_sp@data

xs_dims_planform_sp <- arc2sp("Z:/Work/Office/Regional/ERDC/EMRRP_Sediment/Methods/fluvgeo/inst/extdata/testing_data.gdb/riffle_floodplain_dims_planform")

flowline_sp <- arc2sp("Z:/Work/Office/Regional/ERDC/EMRRP_Sediment/Methods/fluvgeo/inst/extdata/testing_data.gdb/flowline")

dem <- "Z:/Work/Office/Regional/ERDC/EMRRP_Sediment/Methods/fluvgeo/inst/extdata/testing_raster.gdb/dem_1m"

banklines_sp <- arc2sp("Z:/Work/Office/Regional/ERDC/EMRRP_Sediment/Methods/fluvgeo/inst/extdata/testing_data.gdb/banklines")

features_sp <- arc2sp("Z:/Work/Office/Regional/ERDC/EMRRP_Sediment/Methods/fluvgeo/inst/extdata/testing_data.gdb/features")

extent_factor <- 2
streams <- c("Sinsinawa")
regions <- c("Illinois River", "IL River Panther Creek", "IL River LTE 120", "IL River LTE 300")
output_dir <- "Z:/Work/Office/Regional/ERDC/EMRRP_Sediment/Sites2/Sinsinawa_05414820"
output_format <- "word_document"
```

```{r}
# Create the xs Metrics Report
xs_metrics_report(xs_points = xs_points_df,
                  xs_dims_planform = xs_dims_planform_sp,
                  flowline = flowline_sp,
                  dem = dem,
                  banklines = banklines_sp,
                  extent_factor = extent_factor,
                  streams = streams,
                  regions = regions,
                  features = features_sp,
                  label_xs = TRUE,
                  output_dir = output_dir,
                  output_format = output_format)
```
