---
title: "FluvialGeomorph Level 1 Report"
params:
  stream: ""
  flowline_sf: ""
  cross_section_sf: ""
  features_sf: ""
  flowline_pts_sf_list: ""
  xs_points_sf_list: ""
  dem: ""
  show_xs_map: FALSE
  profile_units: ""
  aerial: TRUE
  elevation: FALSE
  xs_label_freq: 5
  exaggeration: 10
  extent_factor: 1.1
  output_format: ""
---

```{r library, eval=TRUE, include=FALSE}
library(fluvgeo)
library(sf)
library(dplyr)
library(knitr)
library(pander)
library(ggplot2)
library(ggrepel)
library(tmap)
library(terra)
library(terrainr)
```

## Study Area Overview
```{r aerial_overview, echo=FALSE, warning=FALSE, message=FALSE, results="hide", fig.width=7, fig.height=7, fig.cap="Reach Overview Map"}
if(aerial) {
  print(fluvgeo::map_reach_overview(flowline = params$flowline_sf, 
                                    cross_section = params$cross_section_sf,
                                    background = "aerial",
                                    xs_label_freq = params$xs_label_freq,
                                    extent_factor = params$extent_factor))
}
```

```{r elevation_overview, echo=FALSE, warning=FALSE, message=FALSE, results="hide", fig.width=7, fig.height=7, fig.cap="Reach Elevation Map"}
if(elevation) {
  print(fluvgeo::map_reach_overview(flowline = params$flowline_sf, 
                                    cross_section = params$cross_section_sf,
                                    background = "elevation",
                                    xs_label_freq = params$xs_label_freq,
                                    exaggeration = params$exaggeration,
                                    extent_factor = params$extent_factor))
}
```

## Longitudinal Profile
```{r long_profile, echo=FALSE, fig.width=7, fig.height=5, fig.cap="Longitudinal Profile Plot"}
print(fluvgeo::compare_long_profile(stream = params$stream,
                            flowline_pts_sf_list = params$flowline_pts_sf_list,
                            features_sf = params$features_sf,
                            profile_units = params$profile_units))
```

```{r xs_long_profile, echo=FALSE, fig.width=7, fig.height=5, fig.cap="XS Longitudinal Profile Plot"}
print(fluvgeo::compare_xs_long_profile(stream = params$stream,
                                     xs_pts_sf_list = params$xs_points_sf_list,
                                     features_sf = params$features_sf,
                                     xs_label_freq = params$xs_label_freq,
                                     profile_units = params$profile_units))
```

## Cross Section Metrics
```{r, xs_metrics_plot, eval=TRUE, echo=FALSE, results='asis', fig.width=7, fig.height=9, fig.cap="Cross Section Metrics Plot.", warning=FALSE}
print(fluvgeo::xs_metrics_plot_L1(xs_dims_sf = params$cross_section_sf,
                                  features_sf = params$features_sf,
                                  xs_label_freq = params$xs_label_freq,
                                  profile_units = params$profile_units))
```


## Cross Section Profiles
```{r cross_section_plots, echo=FALSE, results='asis', fig.width=7, fig.height=4, warning=FALSE, error=FALSE, message=FALSE}
if(params$show_xs_map) {
  # Get dem raster
  dem_rast <- fluvgeo::gdb_raster2SpatRast(raster_path = params$dem)
}

# Ensure that cross sections are sequentially ordered
cross_section <- dplyr::arrange(params$cross_section_sf, Seq)

# Iterate through cross sections
for(j in unique(cross_section$Seq)) {
  if(params$show_xs_map) {
    # Create the cross section plot
    print(fluvgeo::map_xs(cross_section = params$cross_section_sf,
                          xs_number = j,
                          dem = dem_rast,
                          extent_factor = params$extent_factor))
  }
  print(fluvgeo::xs_compare_plot_L1(stream = stream,
                                    xs_number = j,
                                    xs_pts_sf_list = xs_pts_sf_list))
  # Insert vertical white space so that next figure in loop is recognized
  cat('\n')
  # Must set chunk option`results='asis'` to ensure table is drawn properly
}
```


Version: 0.1.48

