test_that("polygon combination dissolves shared borders and preserves detached parts", {
  square <- function(x) sf::st_polygon(list(rbind(c(x,40),c(x+1,40),c(x+1,41),c(x,41),c(x,40))))
  x <- sf::st_sf(name=c("A","B"),geometry=sf::st_sfc(square(-90),square(-89),crs=4326))
  before <- sf::sf_use_s2()
  y <- combine_study_area_polygons(x)
  expect_equal(y$selected_features, 2)
  expect_equal(y$polygon_parts, 1)
  expect_equal(nrow(y$boundary), 1)
  expect_equal(sf::st_crs(y$boundary)$epsg, 4326)
  expect_false("name" %in% names(y$boundary))
  expect_equal(sf::sf_use_s2(), before)
  sf::st_geometry(x)[[2]] <- square(-85)
  expect_equal(combine_study_area_polygons(x)$polygon_parts, 2)
  expect_error(combine_study_area_polygons(x[0,]), "Select")
  expect_error(combine_study_area_polygons(sf::st_set_crs(x,NA)), "CRS")
  point <- sf::st_sf(geometry=sf::st_sfc(sf::st_point(c(-90,40)),crs=4326))
  expect_error(combine_study_area_polygons(point), "polygon|geometry")
  ring <- sf::st_polygon(list(rbind(c(-90,40),c(-88,40),c(-88,42),c(-90,42),c(-90,40)),
    rbind(c(-89.8,40.2),c(-89.8,40.8),c(-89.2,40.8),c(-89.2,40.2),c(-89.8,40.2))))
  hole <- combine_study_area_polygons(sf::st_sf(geometry=sf::st_sfc(ring,crs=4326)))
  expect_equal(length(sf::st_geometry(hole$boundary)[[1]]),2)
})
