test_that("analysis CRS resolves projected definitions and rejects other coordinate spaces", {
  x <- validate_study_analysis_crs("26915")
  expect_equal(x$epsg, 26915)
  expect_match(x$unit, "met")
  expect_identical(validate_study_analysis_crs(x$wkt)$wkt, x$wkt)
  expect_match(validate_study_analysis_crs(2276)$unit, "foot")
  expect_error(validate_study_analysis_crs(4326), "projected")
  expect_error(validate_study_analysis_crs(4978), "projected")
  expect_error(validate_study_analysis_crs(7405), "projected")
  expect_error(validate_study_analysis_crs("not a CRS"), "resolved")
  expect_error(validate_study_analysis_crs(NA_character_), "Enter")
  expect_error(validate_study_analysis_crs(c(26915, 26916)), "Enter")
})

test_that("CRS persistence retains geometry, earlier revisions and vertical choices", {
  root <- withr::local_tempdir()
  original <- file.path(root, "study.gpkg")
  boundary <- sf::st_sf(geometry=sf::st_as_sfc(sf::st_bbox(c(xmin=-94,ymin=41,xmax=-93.9,ymax=41.1), crs=4326)))
  start_study_context(original, study_area_name="CRS fixture")
  spatial <- file.path(root,"boundary.gpkg")
  revise_study_context(original, spatial, study_area_boundary=boundary, add_note="Synthetic test polygon")
  vertical <- file.path(root,"vertical.gpkg")
  record_study_analysis_reference(spatial,vertical,"vertical","Unknown","PROJECT_RECORD","No datum evidence","Test analyst")
  before <- read_study_context(vertical)
  hash <- .fg_file_sha256(vertical)
  out <- file.path(root,"crs.gpkg")
  set_study_analysis_crs(vertical,out,"EPSG:26915","Local UTM zone selected for test area","Test analyst")
  after <- read_study_context(out)
  expect_identical(.fg_file_sha256(vertical),hash)
  expect_identical(after$study_area,before$study_area)
  ref <- after$analysis_reference
  expect_equal(sum(ref$component=="horizontal"),1)
  expect_equal(ref$value[ref$component=="vertical"],"Unknown")
  expect_match(ref$value[ref$component=="horizontal"],"PROJCRS",fixed=TRUE)
  again <- file.path(root,"again.gpkg")
  revise_study_context(out,again,study_area_name="Renamed CRS fixture")
  expect_identical(read_study_context(again)$analysis_reference,ref)
  expect_identical(charToRaw(ref$value[ref$component=="horizontal"]),
    charToRaw(validate_study_analysis_crs(26915)$wkt))
  expect_error(set_study_analysis_crs(original,file.path(root,"no-boundary.gpkg"),26915,"Test","Test"),"boundary")
  expect_error(set_study_analysis_crs(vertical,file.path(root,"bad.gpkg"),4326,"Test","Test"),"projected")
  expect_false(file.exists(file.path(root,"bad.gpkg")))
  expect_error(validate_study_analysis_crs(26915,sf::st_sfc(sf::st_point(c(0,0)),crs=4326)),"polygon")
})
