library(fgm)
context("cross_section_dimensions")

xs_dims <- cross_section_dimensions(xs = fgm::sin_riffle_channel_sp,
                                    xs_points = fgm::sin_riffle_channel_points_sp,
                                    bankfull_elevation = 103,
                                    lead_n = 1,
                                    use_smoothing = TRUE,
                                    loess_span = 0.5)

test_that("check fields exist by name", {
  expect_true("Seq"                   %in% colnames(xs_dims))
  expect_true("Z_smooth"              %in% colnames(xs_dims))
  expect_true("upstream_x"            %in% colnames(xs_dims))
  expect_true("upstream_y"            %in% colnames(xs_dims))
  expect_true("downstream_x"          %in% colnames(xs_dims))
  expect_true("downstream_y"          %in% colnames(xs_dims))
  expect_true("upstream_z"            %in% colnames(xs_dims))
  expect_true("downstream_z"          %in% colnames(xs_dims))
  expect_true("upstream_m"            %in% colnames(xs_dims))
  expect_true("downstream_m"          %in% colnames(xs_dims))
  expect_true("rise"                  %in% colnames(xs_dims))
  expect_true("run"                   %in% colnames(xs_dims))
  expect_true("stream_length"         %in% colnames(xs_dims))
  expect_true("valley_length"         %in% colnames(xs_dims))
  expect_true("sinuosity"             %in% colnames(xs_dims))
  expect_true("slope"                 %in% colnames(xs_dims))
  expect_true("bankfull_elevation"    %in% colnames(xs_dims))
  expect_true("drainage_area"         %in% colnames(xs_dims))
  expect_true("xs_area"               %in% colnames(xs_dims))
  expect_true("xs_width"              %in% colnames(xs_dims))
  expect_true("xs_depth"              %in% colnames(xs_dims))
  expect_true("discharge"             %in% colnames(xs_dims))
  expect_true("fp_area"               %in% colnames(xs_dims))
  expect_true("fp_width"              %in% colnames(xs_dims))
  expect_true("fp_depth"              %in% colnames(xs_dims))
  expect_true("xs_width_depth_ratio"  %in% colnames(xs_dims))
  expect_true("xs_entrenchment_ratio" %in% colnames(xs_dims))
  expect_true("watersurface_elev"     %in% colnames(xs_dims))
  expect_true("bankfull_elev"         %in% colnames(xs_dims))
  expect_true("floodprone_elev"       %in% colnames(xs_dims))
})

test_that("check field data type", {
  expect_true(is.numeric(xs_dims$Seq))
  expect_true(is.numeric(xs_dims$Z_smooth))
  expect_true(is.numeric(xs_dims$upstream_x))
  expect_true(is.numeric(xs_dims$upstream_y))
  expect_true(is.numeric(xs_dims$downstream_x))
  expect_true(is.numeric(xs_dims$downstream_y))
  expect_true(is.numeric(xs_dims$upstream_z))
  expect_true(is.numeric(xs_dims$downstream_z))
  expect_true(is.numeric(xs_dims$upstream_m))
  expect_true(is.numeric(xs_dims$downstream_m))
  expect_true(is.numeric(xs_dims$rise))
  expect_true(is.numeric(xs_dims$run))
  expect_true(is.numeric(xs_dims$stream_length))
  expect_true(is.numeric(xs_dims$valley_length))
  expect_true(is.numeric(xs_dims$sinuosity))
  expect_true(is.numeric(xs_dims$slope))
  expect_true(is.numeric(xs_dims$bankfull_elevation))
  expect_true(is.numeric(xs_dims$drainage_area))
  expect_true(is.numeric(xs_dims$xs_area))
  expect_true(is.numeric(xs_dims$xs_width))
  expect_true(is.numeric(xs_dims$xs_depth))

  expect_true(is.numeric(xs_dims$fp_area))
  expect_true(is.numeric(xs_dims$fp_width))
  expect_true(is.numeric(xs_dims$fp_depth))
  expect_true(is.numeric(xs_dims$xs_width_depth_ratio))
  expect_true(is.numeric(xs_dims$xs_entrenchment_ratio))
  expect_true(is.numeric(xs_dims$watersurface_elev))
  expect_true(is.numeric(xs_dims$bankfull_elev))
  expect_true(is.numeric(xs_dims$floodprone_elev))
})
