test_that('real NAVD88 metres convert to international feet without moving the grid', {
  fixture <- Sys.getenv('FLUVGEO_REAL_FEET_INPUTS')
  skip_if(!nzchar(fixture), 'Set FLUVGEO_REAL_FEET_INPUTS to masked-result.rds')
  trial <- readRDS(fixture)
  source <- trial$result$path
  before <- tools::md5sum(source)
  filename <- tempfile(fileext='.tif'); on.exit(unlink(filename))
  result <- terrain_to_international_feet(source, filename)
  x <- terra::rast(source); y <- terra::rast(filename)
  expect_true(terra::compareGeom(x,y,crs=FALSE))
  expect_identical(terra::datatype(y),'FLT4S')
  rc <- expand.grid(row=round(seq(1,terra::nrow(x),length.out=8)),col=round(seq(1,terra::ncol(x),length.out=8)))
  xy <- terra::xyFromCell(x,terra::cellFromRowCol(x,rc$row,rc$col))
  a <- terra::extract(x,xy)[[1]]; b <- terra::extract(y,xy)[[1]]
  expect_true(anyNA(a) && any(!is.na(a)))
  expect_identical(is.na(b),is.na(a))
  expected <- readBin(writeBin(a / 0.3048,raw(),size=4),'numeric',n=length(a),size=4)
  expect_equal(b,expected,tolerance=0)
  metadata <- inspect_terrain_vertical_reference(filename)
  expect_equal(as.character(metadata$internal_compound$vertical_crs$id$code),'8228')
  expect_true(metadata$internal_compound$band_unit %in% c('ft','foot'))
  expect_identical(result$datum_operation,'none')
  expect_identical(tools::md5sum(source),before)
  expect_error(terrain_to_international_feet(source,filename),'new output')
  expect_error(terrain_to_international_feet(filename,tempfile(fileext='.tif')),'NAVD88 metre')
})
