split_fixture <- function(folder) {
  p <- file.path(folder,"start.gpkg")
  start_study_context(p,"Split test")
  boundary <- sf::st_as_sfc(sf::st_bbox(c(xmin=-90.01,ymin=39.99,xmax=-89.99,ymax=40.04),crs=4326))
  q <- file.path(folder,"boundary.gpkg")
  revise_study_context(p,q,study_area_boundary=sf::st_sf(geometry=boundary),add_note="Synthetic")
  lines <- sf::st_sf(source_id=c("101","102"),geometry=sf::st_sfc(
    sf::st_linestring(rbind(c(-90,40),c(-90,40.01))),
    sf::st_linestring(rbind(c(-90,40.01),c(-90,40.02))),crs=4326))
  s <- add_study_stream_corridor(q,file.path(folder,"stream.gpkg"),lines,"Creek",1000,"ft",add_note="Synthetic")
  r <- add_study_reach_corridor(s$context,file.path(folder,"reach.gpkg"),s$stream_id,"101","R1")
  c(r,list(stream_id=s$stream_id))
}
split_point <- function(lat,lon=-90) sf::st_sfc(sf::st_point(c(lon,lat)),crs=4326)

test_that("map splits retain source lineage and permit repeated splitting, addition and combining", {
  folder <- withr::local_tempdir(); r <- split_fixture(folder)
  old <- read_study_context(r$context)
  files <- list.files(folder,full.names=TRUE); hashes <- tools::md5sum(files)
  v <- preview_study_reach_split(r$context,r$reach_id,split_point(40.005,-89.9999))
  expect_gt(v$snap_distance_m,0)
  expect_equal(nrow(v$areas),2L)
  expect_equal(v$source$distance_m,304.8)
  expect_equal(v$areas$reach_id[1],r$reach_id)
  expect_true(all(v$lengths_m>0))
  s <- split_study_reach(r$context,file.path(folder,"split.gpkg"),r$reach_id,split_point(40.005),"Upper")
  context <- read_study_context(s$context)
  expect_equal(context$streams,old$streams)
  expect_equal(context$reaches$reach_id,c(r$reach_id,s$new_reach_id))
  expect_equal(tools::md5sum(files),hashes)
  p <- read_study_stream_segments(s$context,r$stream_id)
  expect_true(p$piece_state)
  expect_equal(nrow(p$pieces),3L)
  expect_equal(sum(p$pieces$source_id=="101"),2L)
  expect_equal(anyDuplicated(p$pieces$piece_id),0L)
  expect_equal(length(p$assigned_selection_ids),2L)
  expect_true(all(check_study_area_containment(context$streams,reaches=context$reaches)$status=="inside"))
  # An unassigned original segment remains available through its explicit piece ID.
  available <- setdiff(p$lines$selection_id,p$assigned_selection_ids)
  a <- add_study_reach_corridor(s$context,file.path(folder,"add.gpkg"),r$stream_id,available,"R2")
  expect_equal(nrow(read_study_context(a$context)$reaches),3L)
  twice <- split_study_reach(a$context,file.path(folder,"twice.gpkg"),s$new_reach_id,split_point(40.0025),"Uppermost","upstream")
  p2 <- read_study_stream_segments(twice$context,r$stream_id)
  expect_equal(nrow(p2$pieces),4L)
  expect_true(any(p2$pieces$parent_piece_id %in% p$pieces$piece_id))
  ids <- read_study_context(twice$context)$reaches$reach_id
  merged <- merge_study_reaches(twice$context,file.path(folder,"merged.gpkg"),ids,ids[1],"Combined")
  expect_equal(nrow(read_study_context(merged$context)$reaches),1L)
  p3 <- read_study_stream_segments(merged$context,r$stream_id)
  expect_equal(length(p3$assigned_selection_ids),4L)
  expect_equal(nrow(preview_study_reach_split(merged$context,ids[1],split_point(40.015))$areas),2L)
})

test_that("split rejects endpoints, distant clicks and dependent Survey Events without writes", {
  folder <- withr::local_tempdir(); r <- split_fixture(folder)
  expect_error(preview_study_reach_split(r$context,r$reach_id,split_point(40)),"endpoint")
  expect_error(preview_study_reach_split(r$context,r$reach_id,split_point(41)),"closer")
  expect_error(split_study_reach(r$context,file.path(folder,"bad.gpkg"),r$reach_id,split_point(40.005),"R1"),"already exists")
  expect_false(file.exists(file.path(folder,"bad.gpkg")))
  args <- read_study_context(r$context)
  args$survey_events <- data.frame(survey_event_id=.fg_generate_uuid(1),reach_id=r$reach_id,survey_year=2010L)
  path <- file.path(folder,"events.gpkg")
  do.call(write_study_context,c(list(dsn=path),args))
  expect_error(preview_study_reach_split(path,r$reach_id,split_point(40.005)),"Survey Events")
  expect_equal(read_study_context(path)$survey_events,args$survey_events)
})
