test_that("vertical specifications distinguish reference, units and epochs", {
  v <- validate_study_vertical_reference("vertical_crs","5703","orthometric","international_foot")
  expect_match(v$crs_wkt,"^VERTCRS")
  expect_equal(v$crs_authority,"EPSG:5703")
  expect_equal(v$unit_to_metre,0.3048)
  expect_equal(v$support_status,"SPECIFIED_NOT_TRANSFORMED")
  expect_equal(validate_study_vertical_reference("vertical_crs","6360","orthometric","us_survey_foot")$unit_to_metre,1200/3937)
  expect_error(validate_study_vertical_reference("vertical_crs","6344"),"standalone vertical")
  expect_error(validate_study_vertical_reference("vertical_crs","7405"),"standalone vertical")
  expect_error(validate_study_vertical_reference("ellipsoidal","4326","ellipsoidal"),"three-dimensional")
  expect_equal(validate_study_vertical_reference("ellipsoidal","6319","ellipsoidal","metre")$crs_authority,"EPSG:6319")
  expect_error(validate_study_vertical_reference("ellipsoidal","6319","orthometric"),"inconsistent")
  expect_error(validate_study_vertical_reference(epoch_status="known",coordinate_epoch=2020),"source evidence")
  expect_error(validate_study_vertical_reference(coordinate_epoch=2020),"cannot carry")
  expect_error(validate_study_vertical_reference(model_version="1"),"model name")
  declared <- validate_study_vertical_reference("declared","NAPGD2022","orthometric","metre",
    "known",2020,"Target epoch selected from project specification")
  expect_equal(declared$coordinate_epoch,2020)
  expect_identical(declared$crs_wkt,"")
  expect_equal(declared$support_status,"INCOMPLETE_OR_UNQUALIFIED")
  dynamic <- sub('VERTCRS["NAVD88 height",','VERTCRS["Test dynamic height",DYNAMIC[FRAMEEPOCH[2000]],',v$crs_wkt,fixed=TRUE)
  d <- validate_study_vertical_reference("vertical_crs",dynamic,"orthometric","metre")
  expect_equal(d$frame_epoch,2000)
  expect_true(is.na(d$coordinate_epoch))
  expect_equal(d$support_status,"EPOCH_WORKFLOW_REQUIRED")
  expect_error(validate_study_vertical_reference("vertical_crs",dynamic,"orthometric","metre","not_applicable"),"epoch-dependent")
  bad <- v; bad$unit_to_metre <- 1
  expect_error(.fg_vertical_reference_check(bad),"disagree")
})

test_that("schema 7 round trips vertical metadata and preserves revisions", {
  root <- withr::local_tempdir(); original <- file.path(root,"study.gpkg")
  start_study_context(original,study_area_name="Vertical fixture",study_area_purpose="Test")
  v <- validate_study_vertical_reference("vertical_crs","5703","orthometric","us_survey_foot",
    "known",2010.0,"Synthetic coordinate epoch evidence","GEOID18","2019","Synthetic model reference")
  hash <- .fg_file_sha256(original); saved <- file.path(root,"vertical.gpkg")
  set_study_vertical_reference(original,saved,v)
  expect_identical(.fg_file_sha256(original),hash)
  expect_identical(read_study_context(saved)$vertical_reference,v)
  expect_identical(read_study_context_summary(saved)$vertical_reference,v)
  expect_equal(sf::st_read(saved,layer="fluvgeo_study_context",quiet=TRUE)$schema,"FLUVGEO_STUDY_CONTEXT_7")
  expect_null(read_study_context(original)$vertical_reference)
  renamed <- file.path(root,"renamed.gpkg")
  revise_study_context(saved,renamed,study_area_name="Renamed")
  expect_identical(read_study_context(renamed)$vertical_reference,v)
  expect_error(set_study_vertical_reference(saved,file.path(root,"same.gpkg"),v),"unchanged")
  expect_error(record_study_analysis_reference(saved,file.path(root,"legacy.gpkg"),"vertical","Other","PROJECT_RECORD","test","test"),"structured")
  unknown <- validate_study_vertical_reference()
  out <- file.path(root,"unknown.gpkg"); set_study_vertical_reference(renamed,out,unknown)
  expect_identical(read_study_context(out)$vertical_reference,unknown)
  expect_equal(read_study_context(out)$analysis_reference$value,c("Unknown","unknown"))
})

test_that("local vertical candidates include NAVD88 with coverage evidence", {
  b <- sf::st_as_sfc(sf::st_bbox(c(xmin=-94,ymin=41,xmax=-93.9,ymax=41.1),crs=4326))
  rows <- study_vertical_crs_candidates(b)
  expect_true(all(c("5703","6360") %in% rows$code))
  expect_equal(rows$coverage[rows$code=="5703"],"Full bounds")
  expect_false(anyDuplicated(rows$code)>0)
})
